### ISSUE TITLE
Support for Infinity Level 4 in config

### ISSUE THREAD

**Issue by NolanHewitt** [Identity-Theft/infinity-rework#1]
Using [create enchantment industry](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry) its possible to get level 4 infinity, but the way this mod is set up currently it has no effect. Would it be possible to add support for a 4th level so we can use both mods without it breaking this? I really like this idea for an infinity rework but I'd like to use it along side that mod.

**Comment by Identity-Theft** [comment]
Since the mod doesn't add level 4, it wouldn't really make sense to have a config for it but instead I could add an option to make the chance of saving an arrow scale by a certain percentage with each level which would allow it to work with levels above 3.

**Comment by NolanHewitt** [comment]
That would be perfect, thank you!

**Comment by Identity-Theft** [comment]
> Since the mod doesn't add level 4, it wouldn't really make sense to have a config for it but instead I could add an option to make the chance of saving an arrow scale by a certain percentage with each level which would allow it to work with levels above 3.

This has been added in 1.2.0.

**Comment by NolanHewitt** [comment]
Thank you, though testing it with the 1.20.1 version of the mod and using the scaling option, it seems like only the base percentage is applied, while the increase per level is not. I tested this by setting the base percentage to 1% and the increase per level to 30%. With infinity level 3 it never saved any arrows. With it set to a base of 50% with a increase per level of 20% it seemed to only save half the arrows instead of 90% of them.

**Comment by Identity-Theft** [comment]
Yep, I just looked through the code, and I was doing the calculation incorrectly in the 1.20.1 version. I will push a fix as soon as possible.

**Comment by Identity-Theft** [comment]
Just pushed a fix.
